[project]
name = "neusoft-academic-affairs-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddddocr>=1.5.6",
    "fastapi>=0.119.0",
    "uvicorn[standard]>=0.37.0",
    "requests>=2.31.0",
    "rich>=13.0.0",
]
